# Generated by Django 2.1.2 on 2018-11-08 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=32)),
                ('upwd', models.CharField(max_length=50)),
                ('uemail', models.CharField(max_length=50)),
                ('urecvName', models.CharField(default='', max_length=32)),
                ('uaddress', models.CharField(default='', max_length=50)),
                ('upostid', models.CharField(default='', max_length=7)),
                ('utelphone', models.CharField(default='', max_length=11)),
            ],
            options={
                'db_table': 'userinfo',
            },
        ),
    ]
